# GENERATED by bake/export_theme.py -- do not edit.
# Palette roles as shell variables, so no script types a hex value.

NULL_ACCENT="\[\e[38;2;185;204;255m\]"
NULL_BACKGROUND="\[\e[38;2;5;6;10m\]"
NULL_DIM="\[\e[38;2;255;120;0m\]"
NULL_ERROR="\[\e[38;2;255;128;0m\]"
NULL_HIGHLIGHT="\[\e[38;2;165;190;255m\]"
NULL_LINE="\[\e[38;2;35;44;64m\]"
NULL_NEUTRAL="\[\e[38;2;255;239;230m\]"
NULL_SURFACE="\[\e[38;2;12;15;22m\]"
NULL_VOID="\[\e[38;2;0;0;0m\]"
NULL_WARNING="\[\e[38;2;255;177;97m\]"
NULL_RESET="\[\e[0m\]"
