# Installing this system's chrome into a Gecko profile. Sourced, never run.
#
# Firefox and Thunderbird are the same application underneath: the same profile
# layout, the same `profiles.ini`, the same `chrome/userChrome.css`, and the
# same pref that decides whether that stylesheet is read at all. Only four
# things differ between them -- the directory, the binary, the name, and what
# the chrome does once it is loaded.
#
# This exists so there is ONE implementation. Two ninety-line scripts that are
# the same except for a path is exactly the shape that drifts, and drift in this
# project has been silent every single time: a theme regenerated in one place
# and not the other, a check reading the source rather than the artefact, a spec
# claiming a checker that never existed.
#
# THE RULES IT KEEPS, which are the reason the original was written the way it
# was (§9.8):
#
#   chrome/ is OURS entirely, so it is a symlink -- nothing else writes there,
#     and a link means a re-bake reaches the profile without re-running this.
#   user.js may hold the person's OWN preferences, so our block goes BETWEEN
#     MARKERS and is rewritten in place. Appending would drift the moment the
#     generator changed; overwriting would take settings that are not ours.
#   nothing is written without --apply.

# null_gecko_profile <profile root> -> the profile directory, on stdout
#
# The profile the installation actually STARTS with, not the first one listed:
# a profiles.ini can carry several and only one is default.
null_gecko_profile() {
  local moz=$1 ini="$1/profiles.ini" p
  [ -r "$ini" ] || return 1
  p=$(awk -F= '/^\[Install/{i=1} i&&/^Default=/{print $2; exit}' "$ini")
  [ -n "$p" ] || p=$(awk -F= '/^Default=1/{found=1} /^Path=/{path=$2} found&&path{print path; exit}' "$ini")
  [ -n "$p" ] || p=$(awk -F= '/^Path=/{print $2; exit}' "$ini")
  [ -n "$p" ] || return 1
  case "$p" in /*) echo "$p" ;; *) echo "$moz/$p" ;; esac
}

# lib/host.sh answers "is this machine nullLinux", which decides whether a
# profile found here is ours to write to.
. "$(dirname -- "${BASH_SOURCE[0]}")/host.sh" 2>/dev/null || true

# null_gecko_apply <name> <config dir> <profile root> <binary> <apply 0|1>
null_gecko_apply() {
  local name=$1 src=$2 moz=$3 bin=$4 apply=$5
  local mark_a="// >>> nullLinux (generated by bin/null-$name) -- do not edit inside"
  local mark_b="// <<< nullLinux"

  [ -d "$src/chrome" ] || {
    echo "null-$name: no $src (run bake/make_web.py)" >&2; return 1; }

  local profile
  profile=$(null_gecko_profile "$moz") || profile=""
  if [ -z "$profile" ] || [ ! -d "$profile" ]; then
    echo "no $name profile found"
    if [ "$apply" -eq 0 ]; then echo "would create one at $moz/nulllinux"; return 0; fi
    command -v "$bin" >/dev/null 2>&1 || {
      echo "REFUSING: $bin is not installed" >&2; return 1; }
    mkdir -p "$moz"
    "$bin" --headless --CreateProfile "nullLinux $moz/nulllinux" >/dev/null 2>&1
    profile="$moz/nulllinux"
    [ -d "$profile" ] || { echo "REFUSING: could not create a profile" >&2; return 1; }
    echo "created $profile"
  fi
  echo "profile: $profile"

  if [ "$apply" -eq 0 ]; then
    echo "would link  $profile/chrome -> $src/chrome"
    if [ -e "$profile/user.js" ]; then
      if grep -qF "$mark_a" "$profile/user.js" 2>/dev/null; then
        echo "would rewrite the existing nullLinux block in $profile/user.js"
      else
        echo "would append a marked nullLinux block to $profile/user.js (backing it up)"
      fi
    else
      echo "would create $profile/user.js with a marked nullLinux block"
    fi
    echo
    echo "nothing written. Re-run with --apply."
    return 0
  fi

  # A PROFILE ON A MACHINE THAT IS NOT THIS SYSTEM BELONGS TO SOMEBODY ELSE.
  #
  # Run on the development machine, this found /root/.mozilla/firefox/rice --
  # the profile of the system nullLinux replaces -- and would have written this
  # distribution's chrome into it. The tool is not wrong to act on the machine
  # it is running on; it is wrong to do that to a machine that is a different
  # system.
  #
  # Refused rather than guarded silently, and it names the profile it declined
  # to touch, because a tool that quietly does nothing is worse than one that
  # says why.
  if ! null_is_nulllinux 2>/dev/null && [ "${NULL_ALLOW_FOREIGN_PROFILE:-0}" != 1 ]; then
    echo "REFUSING: this is $(null_host_description 2>/dev/null || echo 'not nullLinux')," >&2
    echo "  and $profile is that system's profile, not this one's." >&2
    echo "  NULL_ALLOW_FOREIGN_PROFILE=1 if you mean it." >&2
    return 1
  fi

  ln -sfn "$src/chrome" "$profile/chrome"
  echo "  linked $profile/chrome"

  local target="$profile/user.js"
  if [ -e "$target" ] && ! grep -qF "$mark_a" "$target"; then
    cp -a "$target" "$target.null-backup-$(date +%Y%m%d-%H%M%S)"
    echo "  backed up the existing user.js"
  fi
  python3 - "$target" "$src/user.js" "$mark_a" "$mark_b" <<'PY'
import sys, pathlib
target, src, a, b = sys.argv[1:5]
p = pathlib.Path(target)
block = a + "\n" + pathlib.Path(src).read_text().rstrip() + "\n" + b + "\n"
old = p.read_text() if p.exists() else ""
if a in old and b in old:
    head, rest = old.split(a, 1)
    _, tail = rest.split(b, 1)
    new = head + block + tail.lstrip("\n")
    what = "rewrote the nullLinux block"
else:
    new = (old.rstrip() + "\n\n" if old.strip() else "") + block
    what = "added the nullLinux block"
p.write_text(new)
print(f"  {what} in {target}")
PY

  echo
  echo "The chrome stylesheet is ignored entirely, and in silence, unless"
  echo "toolkit.legacyUserProfileCustomizations.stylesheets is true -- which the"
  echo "block above sets. It takes effect at the next start."
}
