// GENERATED by bake/make_web.py -- do not edit.
// Installed by bin/null-thunderbird, which joins rather than overwrites (§9.8).

// Without this the chrome stylesheet is ignored ENTIRELY and in silence.
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);

// TRANSPORT SECURITY, SET HERE RATHER THAN LEFT TO A CHECKBOX.
//
// Thunderbird's account wizard will accept a plaintext server if that is what
// autoconfig reports. These make the insecure answer something a person has to
// choose deliberately per account rather than something they get by not
// looking. `socketType` 3 is SSL/TLS and 2 is STARTTLS; 0 is plaintext.
user_pref("mail.smtpserver.default.try_ssl", 3);
user_pref("mail.server.default.socketType", 3);
user_pref("mailnews.auto_config.guess.sslIsRequired", true);
user_pref("security.tls.version.min", 3);          // TLS 1.2 or better

// Remote content in mail is a tracking pixel until proven otherwise. This is
// Thunderbird's default and it is set explicitly because it is load-bearing.
user_pref("mailnews.message_display.disable_remote_image", true);

// HTML mail is rendered as plain text where the sender sent both. The
// alternative is running somebody else's layout in a window you trust.
user_pref("mailnews.display.prefer_plaintext", false);
user_pref("mailnews.display.html_as", 0);

// No telemetry, and no start page fetched over the network.
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("mailnews.start_page.enabled", false);

// The same typeface as everything else. An outline build, because a bitmap
// font would be scaled by the engine (§8.10).
user_pref("font.name.monospace.x-western", "Terminus (TTF)");
user_pref("font.name.sans-serif.x-western", "Terminus (TTF)");
user_pref("font.default.x-western", "monospace");
user_pref("font.size.monospace.x-western", 14);
