#!/usr/bin/env bash
# THE EDITOR IS NANO, IN THREE PLACES THAT MUST AGREE.
#
# nano is what James prefers and the only editor themed from the palette
# (config/nano/nanorc, generated by bake/export_theme.py). Independent sites
# choose an editor, and two of them once drifted:
#
#   bin/null-open        editor role -> first("nano" ...)     nano first  (right)
#   config/shell/null.sh EDITOR export -> nvim, vim, nano     nano LAST   (wrong)
#
# The second held only by luck -- @core ships vim-minimal, which provides `vi`
# and not `vim`, so `command -v vim` missed and it fell through to nano. The day
# anything pulls in vim-enhanced or a user adds nvim, EDITOR would flip to an
# unthemed editor against a stated preference, silently. Nothing checked it.
#
# Since 2026-09-09 the order's PRIMARY home is bin/null-defaults (its `progs
# editor` list, which null-open asks first through `null-defaults resolve`);
# null-open keeps a fallback list for a machine where null-defaults is absent.
# This asserts all three sites put nano first, AND behaviourally that the
# resolver and the shell config on a machine that has nano actually yield nano.
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1
fail=0
note() { printf '  %s\n' "$*"; }
[ -r lib/source.sh ] && . lib/source.sh || { note "lib/source.sh gone"; exit 1; }

# 1. The editor order names nano before any other editor, at both code sites.
#    A plain grep, not null_code_only, because that strips quoted strings -- and
#    the editor NAMES are the quoted strings we need to see. Guard against a
#    comment line by requiring the `editor)` case arm itself.
#
#    1a. bin/null-defaults' list -- the primary order.
lst=$(grep -E '^[[:space:]]*editor\)[[:space:]]*echo[[:space:]]+"' bin/null-defaults | head -1)
if printf '%s' "$lst" | grep -qE 'echo[[:space:]]+"nano[[:space:]"]'; then
  note "ok    null-defaults lists nano first for the editor"
else
  note "null-defaults' editor list does not start with nano: ${lst:-<not found>}"; fail=1
fi
#    1b. bin/null-open's fallback, for a machine where null-defaults is absent.
line=$(grep -E '^[[:space:]]*editor\)' bin/null-open | head -1)
if printf '%s' "$line" | grep -qE 'first[[:space:]]+("nano"|nano)([[:space:]]|$)'; then
  note "ok    null-open's fallback opens the editor role with nano"
else
  note "null-open's editor fallback does not start with nano: ${line:-<not found>}"; fail=1
fi
#    1c. Behavioural: the resolver answers nano. Under an EMPTY config home, so a
#        person's own deliberate choice (~/.config/nulllinux/defaults) cannot fail
#        the suite -- the invariant is the DEFAULT, not everybody's preference.
if command -v nano >/dev/null 2>&1; then
  empty=$(mktemp -d)
  got=$(XDG_CONFIG_HOME="$empty" NULL_ROOT="$PWD" bin/null-defaults resolve editor 2>/dev/null)
  rmdir "$empty" 2>/dev/null
  if [ "$got" = nano ]; then
    note "ok    null-defaults resolves the editor to nano"
  else
    note "null-defaults resolves the editor to '${got:-<nothing>}', not nano"; fail=1
  fi
fi

# 2. The shell config exports nano before vim/nvim (code, not prose).
blk=$(null_code_only config/shell/null.sh 2>/dev/null | grep -nE 'EDITOR=(nano|vim|nvim|vi)\b')
first_editor=$(printf '%s\n' "$blk" | grep -oE 'EDITOR=(nano|vim|nvim|vi)' | head -1 | cut -d= -f2)
if [ "$first_editor" = nano ]; then
  note "ok    config/shell/null.sh prefers nano"
else
  note "config/shell/null.sh prefers '$first_editor', not nano"; fail=1
fi

# 3. Behavioural: sourcing the config where nano exists yields EDITOR=nano.
if command -v nano >/dev/null 2>&1; then
  got=$(env -i HOME="$HOME" PATH="$PATH" NULL_ROOT="$PWD" \
        bash -c '. config/shell/null.sh 2>/dev/null; printf "%s" "$EDITOR"' 2>/dev/null)
  if [ "$got" = nano ]; then
    note "ok    sourcing the shell config yields EDITOR=nano (and VISUAL, SUDO_EDITOR follow)"
  else
    note "sourcing the shell config yielded EDITOR='$got', not nano"; fail=1
  fi
else
  note "(nano not on this host, so the behavioural check is skipped)"
fi

[ $fail = 0 ] && echo "PASS: nano is the editor, and both sites that choose one agree"
exit $fail
