#!/usr/bin/env python3
"""Emit compositor colours from the derived palette (NULL.md §1.1, §4.6).

Nobody chooses a hex value. The emissive roles come out of the physics and the
chrome neutrals are chosen but LABELLED as chosen. This generator is what keeps
that true of the compositor's own decorations rather than only of the surfaces
this system draws itself.

Derived, so not committed (§5.7).
"""
import json, sys
from pathlib import Path

meta = json.loads(Path("assets/palette.json").read_text())
r = {k: v["hex"] for k, v in meta["roles"].items()}

out = [
    "# GENERATED by bake/export_theme.py from assets/palette.json -- do not edit.",
    "# Emissive roles are sampled from the Planckian locus and are physics;",
    "# chrome neutrals are chosen, and are labelled as chosen in the palette.",
    "",
]
for name, hexv in sorted(r.items()):
    origin = meta["roles"][name]["origin"]
    # The comment goes ABOVE, never on the same line. `set` takes the REST OF
    # THE LINE as its value, so a trailing comment becomes part of the colour
    # and every use of it expands to a paragraph. Caught by validation, which
    # reported the error while still exiting 0 -- the output is the evidence,
    # not the status (§10.1).
    out.append(f"# {origin}")
    out.append(f"set $c_{name} {hexv}")
out += [
    "",
    "# client.<state> <border> <background> <text> <indicator> <child_border>",
    "#",
    "# A control is a mark and a rule, not a box (§7.1): the focused window is",
    "# distinguished by a RULE in the accent colour, and unfocused windows carry",
    "# no border at all rather than a dimmer box.",
    f"client.focused          $c_accent $c_background $c_neutral $c_accent $c_accent",
    f"client.focused_inactive $c_line $c_background $c_dim $c_line $c_line",
    f"client.unfocused        $c_background $c_background $c_dim $c_background $c_background",
    f"client.urgent           $c_error $c_background $c_neutral $c_error $c_error",
    f"client.background       $c_background",
    "",
]
Path("config/sway/colours.conf").write_text("\n".join(out) + "\n")

# --- the terminal ------------------------------------------------------
# Colours WITHOUT the leading '#', which is what this file format wants.
#
# The sixteen ANSI slots cannot all come from the locus: a blackbody curve
# passes through orange, white and blue and contains no green, cyan or
# magenta at any temperature (§4.8). Those four are the OFF-LOCUS tier --
# chosen, not physics -- and they are labelled as such here rather than
# quietly presented as derived.
def bare(x): return r[x].lstrip("#")

OFF_LOCUS = {           # §4.8 tier 3: chosen, placed at the locus anchors'
    "green":   "6ba368",  # lightness and chroma so they sit with the physics
    "cyan":    "5c9ea6",
    "magenta": "a76ea0",
    "red":     "c25a4a",
}

foot = f"""# GENERATED by bake/export_theme.py -- do not edit.
#
# The font is pinned to a REAL STRIKE. A size with no strike is silently
# scaled by fontconfig on this system (§9.3), and a scaled bitmap is the one
# thing this design exists to avoid. Bold and italic are pinned too: leaving
# them to be derived gets an outline face from fontconfig, which is a second
# typeface on a surface that is supposed to have one (I2).
font=Terminus:pixelsize=18
font-bold=Terminus:pixelsize=18:weight=bold
font-italic=Terminus:pixelsize=18
font-bold-italic=Terminus:pixelsize=18:weight=bold

[cursor]
color={bare("background")} {bare("accent")}

[colors]
background={bare("background")}
foreground={bare("neutral")}

# 0-7 normal, 8-15 bright. The emissive slots are sampled from the Planckian
# locus and are physics; the four off-locus hues are chosen (§4.8).
regular0={bare("background")}
regular1={OFF_LOCUS["red"]}
regular2={OFF_LOCUS["green"]}
regular3={bare("warning")}
regular4={bare("accent")}
regular5={OFF_LOCUS["magenta"]}
regular6={OFF_LOCUS["cyan"]}
regular7={bare("neutral")}
bright0={bare("line")}
bright1={bare("error")}
bright2={OFF_LOCUS["green"]}
bright3={bare("warning")}
bright4={bare("highlight")}
bright5={OFF_LOCUS["magenta"]}
bright6={OFF_LOCUS["cyan"]}
bright7={bare("neutral")}
"""
Path("config/foot").mkdir(parents=True, exist_ok=True)
Path("config/foot/foot.ini").write_text(foot)

# --- the virtual console -------------------------------------------------
#
# THE CONSOLE HAD THE LINUX DEFAULTS. Before the greeter appears, and on every
# tty, the sixteen colours were the kernel's own -- the bright primaries every
# Linux machine has had since 1992, in a system whose entire palette is
# blackbody. The one surface guaranteed to be seen on every boot, and the only
# one still wearing somebody else's colours.
#
# setvtrgb takes three lines of sixteen comma-separated decimals: all the reds,
# then all the greens, then all the blues. Derived from the SAME sixteen the
# terminal uses, two lines above, so the console and foot cannot disagree.
VT = [bare("background"), OFF_LOCUS["red"],  OFF_LOCUS["green"],   bare("warning"),
      bare("accent"),     OFF_LOCUS["magenta"], OFF_LOCUS["cyan"], bare("neutral"),
      bare("line"),       bare("error"),    OFF_LOCUS["green"],    bare("warning"),
      bare("highlight"),  OFF_LOCUS["magenta"], OFF_LOCUS["cyan"], bare("neutral")]
rows = [[int(c[i:i+2], 16) for c in VT] for i in (0, 2, 4)]
Path("config/vconsole").mkdir(parents=True, exist_ok=True)
Path("config/vconsole/vtrgb").write_text(
    "\n".join(",".join(str(v) for v in row) for row in rows) + "\n")

# --- the shell ---------------------------------------------------------
sh = ["# GENERATED by bake/export_theme.py -- do not edit.",
      "# Palette roles as shell variables, so no script types a hex value.", ""]
for name, hexv in sorted(r.items()):
    rgb = tuple(int(hexv[i:i+2], 16) for i in (1, 3, 5))
    sh.append(f'NULL_{name.upper()}="\\[\\e[38;2;{rgb[0]};{rgb[1]};{rgb[2]}m\\]"')
sh.append('NULL_RESET="\\[\\e[0m\\]"')
Path("config/shell").mkdir(parents=True, exist_ok=True)
Path("config/shell/colours.sh").write_text("\n".join(sh) + "\n")

# --- the toolkit -------------------------------------------------------
# §8.10: declaring theme colour NAMES is not enough. The default theme is
# compiled from a stylesheet language and bakes most of its colours in as
# literals, so declaring the names changes only the parts that still reference
# them -- producing an application in the stock grey with your icons and your
# font, which looks like a partial success and is a total one. The SURFACES are
# named explicitly below.
gtk_css = f"""/* GENERATED by bake/export_theme.py -- do not edit. */

@define-color theme_bg_color {r['background']};
@define-color theme_base_color {r['background']};
@define-color theme_fg_color {r['neutral']};
@define-color theme_text_color {r['neutral']};
@define-color theme_selected_bg_color {r['accent']};
@define-color theme_selected_fg_color {r['background']};
@define-color borders {r['line']};
@define-color insensitive_fg_color {r['dim']};

/* Naming the colours above is NOT enough -- these are the surfaces. */
window, dialog, .background,
notebook, notebook > stack,
paned, box, grid, viewport, scrolledwindow {{
    background-color: {r['background']};
    color: {r['neutral']};
}}

headerbar, .titlebar, toolbar, .toolbar, actionbar {{
    background-color: {r['background']};
    color: {r['neutral']};
    border-color: {r['line']};
    box-shadow: none;
    background-image: none;
}}

/* One background (§7.1). The lifted tone is for genuinely raised elements. */
popover, menu, .menu, .context-menu, tooltip {{
    background-color: {r['surface']};
    color: {r['neutral']};
    border: 1px solid {r['line']};
}}

treeview.view, list, row, .view, textview, textview text {{
    background-color: {r['background']};
    color: {r['neutral']};
}}
treeview.view:selected, list row:selected, .view:selected, row:selected {{
    background-color: {r['accent']};
    color: {r['background']};
}}
treeview.view header button {{
    background-color: {r['background']};
    color: {r['dim']};
    border-color: {r['line']};
}}

entry, spinbutton, searchbar entry {{
    background-color: {r['background']};
    color: {r['neutral']};
    border: 1px solid {r['line']};
    border-radius: 0;
}}

/* A control is a mark and a rule, not a box (§7.1): flat, square, and the
   live one distinguished by a rule rather than by a filled rectangle. */
button {{
    background-image: none;
    background-color: transparent;
    color: {r['neutral']};
    border: 1px solid transparent;
    border-radius: 0;
    box-shadow: none;
}}
button:hover  {{ border-bottom-color: {r['line']}; }}
button:active, button:checked {{
    border-bottom-color: {r['accent']};
    color: {r['accent']};
    background-color: transparent;
}}

sidebar, placessidebar, placessidebar list {{
    background-color: {r['background']};
    color: {r['neutral']};
}}
separator {{ background-color: {r['line']}; }}
scrollbar {{ background-color: {r['background']}; border: none; }}
scrollbar slider {{ background-color: {r['line']}; border-radius: 0; min-width: 6px; }}
selection {{ background-color: {r['accent']}; color: {r['background']}; }}
"""
Path("config/gtk-3.0").mkdir(parents=True, exist_ok=True)
Path("config/gtk-3.0/gtk.css").write_text(gtk_css)

# THE NAMES THIS FILE WRITES ARE THE NAMES bin/null-install CREATES.
#
# This wrote gtk-theme-name=Default and gtk-icon-theme-name=Adwaita, from
# before /usr/share/themes/nullLinux and /usr/share/icons/nullLinux existed --
# and it OVERWRITES config/gtk-{3.0,4.0}/settings.ini, so running the bake put
# them back every time. The committed files said nullLinux, the generator that
# owns them said Default, and check-theme-names only ever looked at the output.
# One re-bake and GTK falls back to its built-in LIGHT palette, silently, which
# is the exact failure §8.10 and that check exist for.
#
# Dark remains a FLAG, not a theme name: there is no -dark variant to name, and
# naming one would fall back to light for a different reason.
settings_ini = """[Settings]
gtk-theme-name=nullLinux
gtk-application-prefer-dark-theme=1
gtk-font-name=Terminus 12
gtk-icon-theme-name=nullLinux
gtk-cursor-theme-name=Adwaita
gtk-enable-animations=0
gtk-primary-button-warps-slider=0
"""
Path("config/gtk-3.0/settings.ini").write_text(settings_ini)
Path("config/gtk-4.0").mkdir(parents=True, exist_ok=True)
Path("config/gtk-4.0/gtk.css").write_text(gtk_css)
Path("config/gtk-4.0/settings.ini").write_text(settings_ini)

print("config/gtk-3.0/{gtk.css,settings.ini} written")
print("config/gtk-4.0/{gtk.css,settings.ini} written")
print(f"config/sway/colours.conf written from {len(r)} palette roles")
print("config/foot/foot.ini written")
print("config/vconsole/vtrgb written (16 colours, same as the terminal)")
print("config/shell/colours.sh written")
for n in sorted(r): print(f"  $c_{n:<11} {r[n]}")
