#!/usr/bin/env python3
"""The web class: browser chrome, and an empty state that carries the hero.

NULL.md §8.10.

Two facts decide everything here.

**The font must be the outline build.** Measured, not assumed
(verify/check-font-substitution.py): the .otb bitmap build DOES render in both
WebKit and Gecko -- so the spec's "a bitmap font will not render in a browser
engine" is not what happens. What happens is harder to catch: the engines
SCALE it, producing widths exactly proportional to the requested size, so at
any size that is not one of the nine strikes the text is a scaled bitmap. The
outline build has no strikes to miss.

**Deslopping is default-deny.** Hide the container, then allow back the few
things wanted. Allow-listing what to hide is a standing commitment to track
someone else's release notes for ever, and it loses quietly every time.

The empty state is DRAWN AS TEXT, from the same crop as every other still, so
it arrives on the page's own background instead of sitting on it like a
sticker with its own.
"""

import json
import re
import subprocess
from pathlib import Path

# The repository root from THIS file's location, not the working directory.
# Path.cwd() baked whatever directory the generator happened to be run from
# into the browser preferences, so a checkout that moved left the browser
# pointing at a path that no longer existed.
ROOT = Path(__file__).resolve().parent.parent

RENDER = "render/target/release/render"
SGR = re.compile(r"\x1b\[38;2;(\d+);(\d+);(\d+)m")
# Everything else the renderer emits -- resets above all. Matching only the
# colour sequences leaves the resets in the output as literal "[0m", because
# the ESC itself is non-printing and the bracket is not.
OTHER_ESC = re.compile(r"\x1b\[[0-9;]*m")
FONT = '"Terminus (TTF)", "Terminus", monospace'


def hero_html(cells="assets/logo.cells"):
    """One frame of the hero, as coloured HTML text."""
    out = "/tmp/null-web-still.ans"
    subprocess.run([RENDER, "--file", cells, "still", "--frame", "0", "--out", out],
                   check=True, capture_output=True)
    raw = Path(out).read_text()
    Path(out).unlink(missing_ok=True)

    lines = []
    for row in raw.split("\n"):
        parts, pos, cur = [], 0, None
        for m in SGR.finditer(row):
            text = row[pos:m.start()]
            if text:
                parts.append((cur, text))
            cur = "#%02x%02x%02x" % tuple(int(g) for g in m.groups())
            pos = m.end()
        if row[pos:]:
            parts.append((cur, row[pos:]))
        html = "".join(
            (f'<span style="color:{c}">{esc(OTHER_ESC.sub("", t))}</span>'
             if c else esc(OTHER_ESC.sub("", t)))
            for c, t in parts)
        lines.append(html)
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines)


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def main():
    r = {k: v["hex"] for k, v in
         json.loads(Path("assets/palette.json").read_text())["roles"].items()}
    out = Path("config/firefox")
    (out / "chrome").mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------ empty state
    (out / "newtab.html").write_text(f"""<!doctype html>
<meta charset="utf-8"><title>nullLinux</title>
<style>
  html, body {{ margin:0; height:100%; background:{r['background']}; }}
  body {{ display:flex; align-items:center; justify-content:center; }}
  pre  {{ font-family:{FONT}; font-size:15px; line-height:1.0;
          margin:0; color:{r['neutral']}; }}
</style>
<body><pre>{hero_html()}</pre></body>
""")

    # ---------------------------------------------------------------- chrome
    (out / "chrome" / "userChrome.css").write_text(f"""\
/* GENERATED by bake/make_web.py -- do not edit. */

/* DEFAULT-DENY (§8.10). Everything in the toolbars is hidden, and the few
   things actually wanted are allowed back by name. The alternative -- listing
   what to hide -- is a standing subscription to someone else's release notes,
   and it loses silently every time they add something. */
#nav-bar > *,
#TabsToolbar > *,
#PersonalToolbar {{ display: none !important; }}

/* The address bar does not live directly under the toolbar -- it is inside
   the customization target -- so denying the toolbar's children hides the box
   the wanted things are in. Default-deny has to be applied at EACH level, with
   the container allowed back explicitly, or it takes the whole browser with
   it. (It did: the first version left a window with no chrome at all.) */
#nav-bar > #nav-bar-customization-target {{ display: flex !important; }}
#nav-bar-customization-target > * {{ display: none !important; }}

#nav-bar-customization-target > #urlbar-container,
#nav-bar-customization-target > #back-button,
#nav-bar-customization-target > #forward-button,
#nav-bar > #back-button,
#nav-bar > #forward-button,
#nav-bar > #urlbar-container,
#TabsToolbar > #tabbrowser-tabs {{ display: revert !important; }}

:root {{
  --toolbar-bgcolor: {r['background']} !important;
  --toolbar-color: {r['neutral']} !important;
  --tab-selected-bgcolor: {r['surface']} !important;
  --toolbarbutton-icon-fill: {r['dim']} !important;
  --lwt-accent-color: {r['background']} !important;
  --arrowpanel-background: {r['surface']} !important;
  --arrowpanel-color: {r['neutral']} !important;
  --urlbar-box-bgcolor: {r['surface']} !important;
}}

/* One background (§7.1): a lifted tone only for genuinely raised things. */
#navigator-toolbox, #nav-bar, #TabsToolbar, #urlbar-background {{
  background: {r['background']} !important;
  border-color: {r['line']} !important;
  box-shadow: none !important;
}}
#urlbar, #urlbar-input, .tab-label, #navigator-toolbox {{
  font-family: {FONT} !important;
  font-size: 13px !important;
  color: {r['neutral']} !important;
}}
#urlbar[focused] > #urlbar-background {{ border-color: {r['accent']} !important; }}

.tabbrowser-tab .tab-background {{ background: {r['background']} !important; }}
.tabbrowser-tab[selected] .tab-background {{
  background: {r['surface']} !important;
  border-bottom: 1px solid {r['dim']} !important;
}}
""")

    (out / "chrome" / "userContent.css").write_text(f"""\
/* GENERATED by bake/make_web.py -- do not edit.

   Scoped to the browser's OWN pages. A default-deny rule aimed at arbitrary
   sites would not be deslopping, it would be breaking the web. */
@-moz-document url-prefix("about:blank"), url-prefix("about:newtab"),
               url-prefix("about:home") {{
  :root, body {{ background: {r['background']} !important; }}
}}
""")

    # ----------------------------------------------------------------- prefs
    (out / "user.js").write_text(f"""\
// GENERATED by bake/make_web.py -- do not edit.
// Installed by bin/null-firefox, which joins rather than overwrites (§9.8).

// Without this the chrome stylesheet is ignored ENTIRELY and in silence.
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);

// The empty state, drawn as text from the same crop as every other still.
user_pref("browser.startup.homepage", "file://{ROOT}/config/firefox/newtab.html");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtab.url", "file://{ROOT}/config/firefox/newtab.html");

// Slop the chrome rules cannot reach, because it is generated content.
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("browser.tabs.firefox-view", false);
user_pref("extensions.pocket.enabled", false);
user_pref("browser.aboutConfig.showWarning", false);

// A bitmap-only font would be scaled here; the outline build is the one that
// survives an engine (§8.10).
user_pref("font.name.monospace.x-western", "Terminus (TTF)");
user_pref("font.name.sans-serif.x-western", "Terminus (TTF)");
user_pref("font.default.x-western", "monospace");
user_pref("font.size.monospace.x-western", 14);
""")

    # ================================================================= mail
    #
    # Thunderbird is Gecko, so the same mechanism reaches it: the same
    # profiles.ini, the same chrome/userChrome.css, and the same pref that
    # decides whether that stylesheet is read at all. A mail client in this
    # system's colours is otherwise a thing you cannot have.
    #
    # NOT default-deny here, unlike the browser. Firefox's chrome is hidden and
    # a few things allowed back because a browser's toolbar is somebody else's
    # subscription to their own release notes. A mail client's chrome IS the
    # application -- folder pane, message list, headers -- and hiding it by
    # default would leave a window you cannot read mail in. So this recolours
    # rather than removes.
    mail = Path("config/thunderbird")
    (mail / "chrome").mkdir(parents=True, exist_ok=True)
    (mail / "chrome" / "userChrome.css").write_text(f"""\
/* GENERATED by bake/make_web.py -- do not edit. */

/* The palette, once, as variables the rest of this file uses. Every value
   comes from assets/palette.json; none is typed (§4.8). */
:root {{
  --null-ground:  {r['background']};
  --null-surface: {r['surface']};
  --null-line:    {r['line']};
  --null-text:    {r['neutral']};
  --null-dim:     {r['dim']};
  --null-accent:  {r['accent']};
  --null-error:   {r['error']};
}}

/* Thunderbird ships its own light and dark themes and picks one from the
   system. Both are overridden here, because "dark" is not this system's
   colours -- it is somebody else's idea of dark (§8.10). */
:root, body,
#messengerWindow, #tabmail, #tabpanelcontainer,
#folderPaneBox, #threadPaneBox, #messagepanebox {{
  background-color: var(--null-ground) !important;
  color: var(--null-text) !important;
}}

/* A rule, not a box (§7.1): panes are separated by one line, not by a filled
   panel and a shadow. */
#folderPaneBox, #threadPaneBox {{
  border-right: 1px solid var(--null-line) !important;
  box-shadow: none !important;
}}
#messengerWindow toolbar, #tabs-toolbar, #mail-toolbox {{
  background-color: var(--null-ground) !important;
  border-bottom: 1px solid var(--null-line) !important;
  box-shadow: none !important;
}}

/* Selection is accent-on-ground, the same idiom as the picker and GTK --
   one selection idiom in this system, not three. */
treechildren::-moz-tree-row(selected),
#threadTree tr[data-properties~="selected"] {{
  background-color: var(--null-accent) !important;
  color: var(--null-ground) !important;
}}

/* Unread is a MARK, not a second fill. */
treechildren::-moz-tree-cell-text(unread),
#threadTree tr[data-properties~="unread"] {{
  color: var(--null-accent) !important;
  font-weight: normal !important;
}}

/* No rounded corners anywhere in this system. */
* {{ border-radius: 0 !important; }}
""")

    (mail / "user.js").write_text(f"""\
// GENERATED by bake/make_web.py -- do not edit.
// Installed by bin/null-thunderbird, which joins rather than overwrites (§9.8).

// Without this the chrome stylesheet is ignored ENTIRELY and in silence.
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);

// TRANSPORT SECURITY, SET HERE RATHER THAN LEFT TO A CHECKBOX.
//
// Thunderbird's account wizard will accept a plaintext server if that is what
// autoconfig reports. These make the insecure answer something a person has to
// choose deliberately per account rather than something they get by not
// looking. `socketType` 3 is SSL/TLS and 2 is STARTTLS; 0 is plaintext.
user_pref("mail.smtpserver.default.try_ssl", 3);
user_pref("mail.server.default.socketType", 3);
user_pref("mailnews.auto_config.guess.sslIsRequired", true);
user_pref("security.tls.version.min", 3);          // TLS 1.2 or better

// Remote content in mail is a tracking pixel until proven otherwise. This is
// Thunderbird's default and it is set explicitly because it is load-bearing.
user_pref("mailnews.message_display.disable_remote_image", true);

// HTML mail is rendered as plain text where the sender sent both. The
// alternative is running somebody else's layout in a window you trust.
user_pref("mailnews.display.prefer_plaintext", false);
user_pref("mailnews.display.html_as", 0);

// No telemetry, and no start page fetched over the network.
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("mailnews.start_page.enabled", false);

// The same typeface as everything else. An outline build, because a bitmap
// font would be scaled by the engine (§8.10).
user_pref("font.name.monospace.x-western", "Terminus (TTF)");
user_pref("font.name.sans-serif.x-western", "Terminus (TTF)");
user_pref("font.default.x-western", "monospace");
user_pref("font.size.monospace.x-western", 14);
""")

    n = len((out / "newtab.html").read_text().split("\n"))
    print(f"  config/firefox/newtab.html          {n} lines, hero as text")
    print("  config/firefox/chrome/userChrome.css  default-deny chrome")
    print("  config/firefox/chrome/userContent.css scoped to about: pages")
    print("  config/firefox/user.js                prefs")
    print("  config/thunderbird/chrome/userChrome.css  mail chrome, recoloured")
    print("  config/thunderbird/user.js            prefs, TLS enforced")


if __name__ == "__main__":
    main()
