// GENERATED by bake/make_web.py -- do not edit.
// Installed by bin/null-firefox, which joins rather than overwrites (§9.8).

// Without this the chrome stylesheet is ignored ENTIRELY and in silence.
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);

// The new tab is the browser's STOCK page (James's choice, 2026-09-09): no
// homepage or newtab override here. The prefs below only deslop that stock page.
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("browser.tabs.firefox-view", false);
user_pref("extensions.pocket.enabled", false);
user_pref("browser.aboutConfig.showWarning", false);

// A bitmap-only font would be scaled here; the outline build is the one that
// survives an engine (§8.10).
user_pref("font.name.monospace.x-western", "Terminus (TTF)");
user_pref("font.name.sans-serif.x-western", "Terminus (TTF)");
user_pref("font.default.x-western", "monospace");
user_pref("font.size.monospace.x-western", 14);
